SUBROUTINE DIAG_MAT(N,H,EVAL)!diagonalize input matrx
USE PARS
IMPLICIT NONE
!IN&OUT PUTS
 INTEGER ::N
 REAL(DP)::H(0:NMAX,0:NMAX),EVAL(0:NMAX)
!VARIABLES FOR DIAGONALIZATION
 INTEGER::LWORK,NB,INFO
 REAL(DP),ALLOCATABLE::WORK(:)
 CHARACTER::JOBZ,UPLO
!
 JOBZ='V';UPLO='U'
 IF(.NOT.ALLOCATED(WORK))THEN
    CALL DSYEV(JOBZ,UPLO,NMAX+1,H(0:NMAX,0:NMAX),NMAX+1,&
               EVAL(0:NMAX),EVAL(0:NMAX),-1,INFO)
    LWORK=EVAL(0)
    ALLOCATE(WORK(LWORK))
 ENDIF
!DIAGONALIZATION
 CALL DSYEV(JOBZ,UPLO,N+1,H(0:N,0:N),N+1,&
             EVAL(0:N),WORK,LWORK,INFO)
 RETURN
END SUBROUTINE DIAG_MAT

SUBROUTINE HDIAG_L(NL,L)!DIAGONALIZE THE LTH BLOCK IN FULL H  
USE PARS
USE HMATS
USE EIGENS
IMPLICIT NONE
 INTEGER::NL,L
 INTEGER::S,START,SSTART
 REAL(DP)::HTEMP(0:NMAX,0:NMAX),ETEMP(0:NMAX)
!
 HTEMP(:,:)=0.0D0;ETEMP(:)=0.0D0
 START=SSTART(L)
 DO S=START,NSPIN
    HTEMP(0:NL,0:NL)=HMAT_UU(0:NL,0:NL,S)
    CALL DIAG_MAT(NL,HTEMP,ETEMP)
    EIGVAL_NEW(0:NL,L,S)=ETEMP(0:NL)
    EVEC_UU(0:NL,0:NL,L,S)=HTEMP(0:NL,0:NL)   
 ENDDO
 RETURN
END SUBROUTINE HDIAG_L
