FUNCTION STATE_TOTAL(NSHELL,LUSE) RESULT(RES)!FIND HF STATES NUMBER -1
IMPLICIT NONE
 INTEGER::LUSE,NSHELL,RES
 INTEGER::L,N,S,TOTAL
 TOTAL=0
 DO L=0,LUSE
    N=((NSHELL-1)-L)/2+1
    IF(L==0)TOTAL=TOTAL+N
    IF(L> 0)TOTAL=TOTAL+N*2
 ENDDO
 RES=TOTAL-1
 RETURN
END FUNCTION STATE_TOTAL

FUNCTION NLIMIT(L,NSHELL) RESULT(RES)!FIND THE LARGEST POSSIBLE N VALUE FOR A GIVEN L
IMPLICIT NONE
 INTEGER::L,NSHELL,RES
 RES=(NSHELL-1-L)/2
 RETURN
END FUNCTION NLIMIT

FUNCTION SSTART(L) RESULT(RES)
IMPLICIT NONE
 INTEGER::L,RES
 IF(L==0) RES=1
 IF(L> 0) RES=0
 RETURN
END FUNCTION SSTART

