MODULE PARS
 INTEGER,PARAMETER::DP=8
 INTEGER,PARAMETER::NIORB=100,NMORB=40
 INTEGER,PARAMETER::NMAX=2,LMAX=2,JMAX=5,TMAX=1,NSPIN=1
 INTEGER::NUSE,LUSE,NSHELL
 REAL(DP)::BOSC,HBAR2M,HBROMG!OSCILLATOR LENGTH^(-1)
 REAL(DP)::KAPPAR,KAPPAS,V0R,V0S!COEFFICIENT OF THE POTENTIAL 
END MODULE PARS

MODULE LABELS
USE PARS
 TYPE EINX
  INTEGER::N,L,S
  REAL(DP)::E  
 END TYPE

 TYPE V2INX
  INTEGER::N1,N3,L,J
 END TYPE V2INX
END MODULE LABELS

MODULE ORBINDX
USE PARS
USE LABELS
 TYPE(V2INX)::JLABEL(1:NIORB)
 INTEGER::JORB(0:NMAX,0:NMAX,0:LMAX,0:NSPIN)
END MODULE ORBINDX

MODULE TABLES
USE PARS
 REAL(DP)::VMTAB(0:NMORB,0:NMORB,0:NMORB,0:NMORB)
 INTEGER ::MLABEL(0:NMAX,0:LMAX,1:JMAX,-JMAX:JMAX,0:TMAX)
END MODULE TABLES

MODULE TUMATS
USE PARS
 REAL(DP)::TUMAT(0:NMAX,0:NMAX,0:LMAX)
END MODULE TUMATS

MODULE V2MATS
USE PARS
 REAL(DP)::V2B_UU(1:NIORB,1:NIORB)
END MODULE V2MATS

MODULE VMEANS
USE PARS
 REAL(DP)::VMEAN_UU(0:NMAX,0:NMAX,0:NSPIN)
END MODULE VMEANS

MODULE HMATS
USE PARS
 REAL(DP)::HMAT_UU(0:NMAX,0:NMAX,0:NSPIN)
END MODULE HMATS

MODULE EIGENS
USE PARS
 REAL(DP)::EVEC_UU(0:NMAX,0:NMAX,0:LMAX,0:NSPIN)
 REAL(DP)::EIGVAL(0:NMAX,0:LMAX,0:NSPIN)
 REAL(DP)::EIGVAL_NEW(0:NMAX,0:LMAX,0:NSPIN)
 INTEGER ::DEGENER(0:NMAX,0:LMAX,0:NSPIN)
 INTEGER ::NBELOW(0:LMAX,0:NSPIN)
END MODULE EIGENS

MODULE RHOS
USE PARS
 REAL(DP)::RHO_UU(0:NMAX,0:NMAX,0:LMAX,0:NSPIN)
 REAL(DP)::RHONEW_UU(0:NMAX,0:NMAX,0:LMAX,0:NSPIN)
END MODULE RHOS

